# heavily inspired by https://actuated.dev/blog/multi-arch-docker-github-actions
name: publish

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  publish:
    permissions:
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get Ref Name
        run: echo REF_NAME=${GITHUB_REF_NAME/\//-} >> $GITHUB_ENV
      - name: Get Repo Owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          outputs: "type=registry,push=true"
          provenance: false
          platforms: linux/amd64,linux/arm64/v8
          build-args: |
            Version=${{ env.REF_NAME }}
            GitCommit=${{ github.sha }}
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/openmower-mapeditor:${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER }}/openmower-mapeditor:${{ env.REF_NAME }}
